// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-service-1/service-1.proto

package service1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetService1Request struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetService1Request) Reset()         { *m = GetService1Request{} }
func (m *GetService1Request) String() string { return proto.CompactTextString(m) }
func (*GetService1Request) ProtoMessage()    {}
func (*GetService1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3d78e7957678c8, []int{0}
}

func (m *GetService1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetService1Request.Unmarshal(m, b)
}
func (m *GetService1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetService1Request.Marshal(b, m, deterministic)
}
func (m *GetService1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetService1Request.Merge(m, src)
}
func (m *GetService1Request) XXX_Size() int {
	return xxx_messageInfo_GetService1Request.Size(m)
}
func (m *GetService1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetService1Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetService1Request proto.InternalMessageInfo

func (m *GetService1Request) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetService1Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetService1Response struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetService1Response) Reset()         { *m = GetService1Response{} }
func (m *GetService1Response) String() string { return proto.CompactTextString(m) }
func (*GetService1Response) ProtoMessage()    {}
func (*GetService1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3d78e7957678c8, []int{1}
}

func (m *GetService1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetService1Response.Unmarshal(m, b)
}
func (m *GetService1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetService1Response.Marshal(b, m, deterministic)
}
func (m *GetService1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetService1Response.Merge(m, src)
}
func (m *GetService1Response) XXX_Size() int {
	return xxx_messageInfo_GetService1Response.Size(m)
}
func (m *GetService1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetService1Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetService1Response proto.InternalMessageInfo

func (m *GetService1Response) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetService1Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetOtherService1Request struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOtherService1Request) Reset()         { *m = GetOtherService1Request{} }
func (m *GetOtherService1Request) String() string { return proto.CompactTextString(m) }
func (*GetOtherService1Request) ProtoMessage()    {}
func (*GetOtherService1Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3d78e7957678c8, []int{2}
}

func (m *GetOtherService1Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtherService1Request.Unmarshal(m, b)
}
func (m *GetOtherService1Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtherService1Request.Marshal(b, m, deterministic)
}
func (m *GetOtherService1Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtherService1Request.Merge(m, src)
}
func (m *GetOtherService1Request) XXX_Size() int {
	return xxx_messageInfo_GetOtherService1Request.Size(m)
}
func (m *GetOtherService1Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtherService1Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtherService1Request proto.InternalMessageInfo

func (m *GetOtherService1Request) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetOtherService1Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetOtherService1Response struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOtherService1Response) Reset()         { *m = GetOtherService1Response{} }
func (m *GetOtherService1Response) String() string { return proto.CompactTextString(m) }
func (*GetOtherService1Response) ProtoMessage()    {}
func (*GetOtherService1Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce3d78e7957678c8, []int{3}
}

func (m *GetOtherService1Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtherService1Response.Unmarshal(m, b)
}
func (m *GetOtherService1Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtherService1Response.Marshal(b, m, deterministic)
}
func (m *GetOtherService1Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtherService1Response.Merge(m, src)
}
func (m *GetOtherService1Response) XXX_Size() int {
	return xxx_messageInfo_GetOtherService1Response.Size(m)
}
func (m *GetOtherService1Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtherService1Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtherService1Response proto.InternalMessageInfo

func (m *GetOtherService1Response) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetOtherService1Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetService1Request)(nil), "service1.GetService1Request")
	proto.RegisterType((*GetService1Response)(nil), "service1.GetService1Response")
	proto.RegisterType((*GetOtherService1Request)(nil), "service1.GetOtherService1Request")
	proto.RegisterType((*GetOtherService1Response)(nil), "service1.GetOtherService1Response")
}

func init() { proto.RegisterFile("grpc-service-1/service-1.proto", fileDescriptor_ce3d78e7957678c8) }

var fileDescriptor_ce3d78e7957678c8 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x35, 0xd4, 0x87, 0xb3, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0x38, 0xa0, 0x02, 0x86, 0x4a, 0x0e, 0x5c, 0x42, 0xee, 0xa9, 0x25, 0xc1,
	0x50, 0x6e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x59, 0x62, 0x8e,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x88, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c,
	0x9c, 0x98, 0x9e, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x2a, 0x39, 0x72, 0x09,
	0xa3, 0x98, 0x50, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x4a, 0x92, 0x11, 0xae, 0x5c, 0xe2, 0xee, 0xa9,
	0x25, 0xfe, 0x25, 0x19, 0xa9, 0x45, 0x94, 0xb8, 0xc4, 0x8d, 0x4b, 0x02, 0xd3, 0x18, 0xd2, 0x9d,
	0x63, 0xb4, 0x95, 0x91, 0x8b, 0xc7, 0xbd, 0xa8, 0x20, 0x19, 0x66, 0x88, 0x90, 0x17, 0x17, 0x37,
	0x92, 0x17, 0x85, 0x64, 0xf4, 0x60, 0xc1, 0xa7, 0x87, 0x19, 0x76, 0x52, 0xb2, 0x38, 0x64, 0xa1,
	0x0e, 0x89, 0xe4, 0x12, 0x40, 0x77, 0xa4, 0x90, 0x22, 0x8a, 0x16, 0x6c, 0xe1, 0x20, 0xa5, 0x84,
	0x4f, 0x09, 0xc4, 0xe8, 0x24, 0x36, 0x70, 0xe4, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x7f,
	0xbb, 0x43, 0xdc, 0xfe, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcService1Client is the client API for GrpcService1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcService1Client interface {
	GetService1(ctx context.Context, in *GetService1Request, opts ...grpc.CallOption) (*GetService1Response, error)
	GetOtherService1(ctx context.Context, in *GetOtherService1Request, opts ...grpc.CallOption) (*GetOtherService1Response, error)
}

type grpcService1Client struct {
	cc *grpc.ClientConn
}

func NewGrpcService1Client(cc *grpc.ClientConn) GrpcService1Client {
	return &grpcService1Client{cc}
}

func (c *grpcService1Client) GetService1(ctx context.Context, in *GetService1Request, opts ...grpc.CallOption) (*GetService1Response, error) {
	out := new(GetService1Response)
	err := c.cc.Invoke(ctx, "/service1.GrpcService1/GetService1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcService1Client) GetOtherService1(ctx context.Context, in *GetOtherService1Request, opts ...grpc.CallOption) (*GetOtherService1Response, error) {
	out := new(GetOtherService1Response)
	err := c.cc.Invoke(ctx, "/service1.GrpcService1/GetOtherService1", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcService1Server is the server API for GrpcService1 service.
type GrpcService1Server interface {
	GetService1(context.Context, *GetService1Request) (*GetService1Response, error)
	GetOtherService1(context.Context, *GetOtherService1Request) (*GetOtherService1Response, error)
}

// UnimplementedGrpcService1Server can be embedded to have forward compatible implementations.
type UnimplementedGrpcService1Server struct {
}

func (*UnimplementedGrpcService1Server) GetService1(ctx context.Context, req *GetService1Request) (*GetService1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService1 not implemented")
}
func (*UnimplementedGrpcService1Server) GetOtherService1(ctx context.Context, req *GetOtherService1Request) (*GetOtherService1Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOtherService1 not implemented")
}

func RegisterGrpcService1Server(s *grpc.Server, srv GrpcService1Server) {
	s.RegisterService(&_GrpcService1_serviceDesc, srv)
}

func _GrpcService1_GetService1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetService1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcService1Server).GetService1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service1.GrpcService1/GetService1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcService1Server).GetService1(ctx, req.(*GetService1Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService1_GetOtherService1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtherService1Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcService1Server).GetOtherService1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service1.GrpcService1/GetOtherService1",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcService1Server).GetOtherService1(ctx, req.(*GetOtherService1Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcService1_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service1.GrpcService1",
	HandlerType: (*GrpcService1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetService1",
			Handler:    _GrpcService1_GetService1_Handler,
		},
		{
			MethodName: "GetOtherService1",
			Handler:    _GrpcService1_GetOtherService1_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-service-1/service-1.proto",
}
