// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc-service-2/service-2.proto

package service2

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetService2Request struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetService2Request) Reset()         { *m = GetService2Request{} }
func (m *GetService2Request) String() string { return proto.CompactTextString(m) }
func (*GetService2Request) ProtoMessage()    {}
func (*GetService2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f4dac761b35618, []int{0}
}

func (m *GetService2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetService2Request.Unmarshal(m, b)
}
func (m *GetService2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetService2Request.Marshal(b, m, deterministic)
}
func (m *GetService2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetService2Request.Merge(m, src)
}
func (m *GetService2Request) XXX_Size() int {
	return xxx_messageInfo_GetService2Request.Size(m)
}
func (m *GetService2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetService2Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetService2Request proto.InternalMessageInfo

func (m *GetService2Request) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetService2Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetService2Response struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetService2Response) Reset()         { *m = GetService2Response{} }
func (m *GetService2Response) String() string { return proto.CompactTextString(m) }
func (*GetService2Response) ProtoMessage()    {}
func (*GetService2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f4dac761b35618, []int{1}
}

func (m *GetService2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetService2Response.Unmarshal(m, b)
}
func (m *GetService2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetService2Response.Marshal(b, m, deterministic)
}
func (m *GetService2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetService2Response.Merge(m, src)
}
func (m *GetService2Response) XXX_Size() int {
	return xxx_messageInfo_GetService2Response.Size(m)
}
func (m *GetService2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetService2Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetService2Response proto.InternalMessageInfo

func (m *GetService2Response) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetService2Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetOtherService2Request struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOtherService2Request) Reset()         { *m = GetOtherService2Request{} }
func (m *GetOtherService2Request) String() string { return proto.CompactTextString(m) }
func (*GetOtherService2Request) ProtoMessage()    {}
func (*GetOtherService2Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f4dac761b35618, []int{2}
}

func (m *GetOtherService2Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtherService2Request.Unmarshal(m, b)
}
func (m *GetOtherService2Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtherService2Request.Marshal(b, m, deterministic)
}
func (m *GetOtherService2Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtherService2Request.Merge(m, src)
}
func (m *GetOtherService2Request) XXX_Size() int {
	return xxx_messageInfo_GetOtherService2Request.Size(m)
}
func (m *GetOtherService2Request) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtherService2Request.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtherService2Request proto.InternalMessageInfo

func (m *GetOtherService2Request) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetOtherService2Request) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetOtherService2Response struct {
	Val                  int64    `protobuf:"varint,1,opt,name=val,proto3" json:"val,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOtherService2Response) Reset()         { *m = GetOtherService2Response{} }
func (m *GetOtherService2Response) String() string { return proto.CompactTextString(m) }
func (*GetOtherService2Response) ProtoMessage()    {}
func (*GetOtherService2Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_95f4dac761b35618, []int{3}
}

func (m *GetOtherService2Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOtherService2Response.Unmarshal(m, b)
}
func (m *GetOtherService2Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOtherService2Response.Marshal(b, m, deterministic)
}
func (m *GetOtherService2Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOtherService2Response.Merge(m, src)
}
func (m *GetOtherService2Response) XXX_Size() int {
	return xxx_messageInfo_GetOtherService2Response.Size(m)
}
func (m *GetOtherService2Response) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOtherService2Response.DiscardUnknown(m)
}

var xxx_messageInfo_GetOtherService2Response proto.InternalMessageInfo

func (m *GetOtherService2Response) GetVal() int64 {
	if m != nil {
		return m.Val
	}
	return 0
}

func (m *GetOtherService2Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*GetService2Request)(nil), "service2.GetService2Request")
	proto.RegisterType((*GetService2Response)(nil), "service2.GetService2Response")
	proto.RegisterType((*GetOtherService2Request)(nil), "service2.GetOtherService2Request")
	proto.RegisterType((*GetOtherService2Response)(nil), "service2.GetOtherService2Response")
}

func init() { proto.RegisterFile("grpc-service-2/service-2.proto", fileDescriptor_95f4dac761b35618) }

var fileDescriptor_95f4dac761b35618 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4b, 0x2f, 0x2a, 0x48,
	0xd6, 0x2d, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x35, 0xd2, 0x87, 0xb3, 0xf4, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0x38, 0xa0, 0x02, 0x46, 0x4a, 0x0e, 0x5c, 0x42, 0xee, 0xa9, 0x25, 0xc1,
	0x50, 0x6e, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x00, 0x17, 0x73, 0x59, 0x62, 0x8e,
	0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x88, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c,
	0x9c, 0x98, 0x9e, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe3, 0x2a, 0x39, 0x72, 0x09,
	0xa3, 0x98, 0x50, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x4a, 0x92, 0x11, 0xae, 0x5c, 0xe2, 0xee, 0xa9,
	0x25, 0xfe, 0x25, 0x19, 0xa9, 0x45, 0x94, 0xb8, 0xc4, 0x8d, 0x4b, 0x02, 0xd3, 0x18, 0xd2, 0x9d,
	0x63, 0xb4, 0x95, 0x91, 0x8b, 0xc7, 0xbd, 0xa8, 0x20, 0x19, 0x66, 0x88, 0x90, 0x17, 0x17, 0x37,
	0x92, 0x17, 0x85, 0x64, 0xf4, 0x60, 0xc1, 0xa7, 0x87, 0x19, 0x76, 0x52, 0xb2, 0x38, 0x64, 0xa1,
	0x0e, 0x89, 0xe4, 0x12, 0x40, 0x77, 0xa4, 0x90, 0x22, 0x8a, 0x16, 0x6c, 0xe1, 0x20, 0xa5, 0x84,
	0x4f, 0x09, 0xc4, 0xe8, 0x24, 0x36, 0x70, 0xe4, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x01,
	0xa3, 0xe8, 0xe5, 0xfe, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GrpcService2Client is the client API for GrpcService2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GrpcService2Client interface {
	GetService2(ctx context.Context, in *GetService2Request, opts ...grpc.CallOption) (*GetService2Response, error)
	GetOtherService2(ctx context.Context, in *GetOtherService2Request, opts ...grpc.CallOption) (*GetOtherService2Response, error)
}

type grpcService2Client struct {
	cc *grpc.ClientConn
}

func NewGrpcService2Client(cc *grpc.ClientConn) GrpcService2Client {
	return &grpcService2Client{cc}
}

func (c *grpcService2Client) GetService2(ctx context.Context, in *GetService2Request, opts ...grpc.CallOption) (*GetService2Response, error) {
	out := new(GetService2Response)
	err := c.cc.Invoke(ctx, "/service2.GrpcService2/GetService2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grpcService2Client) GetOtherService2(ctx context.Context, in *GetOtherService2Request, opts ...grpc.CallOption) (*GetOtherService2Response, error) {
	out := new(GetOtherService2Response)
	err := c.cc.Invoke(ctx, "/service2.GrpcService2/GetOtherService2", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrpcService2Server is the server API for GrpcService2 service.
type GrpcService2Server interface {
	GetService2(context.Context, *GetService2Request) (*GetService2Response, error)
	GetOtherService2(context.Context, *GetOtherService2Request) (*GetOtherService2Response, error)
}

// UnimplementedGrpcService2Server can be embedded to have forward compatible implementations.
type UnimplementedGrpcService2Server struct {
}

func (*UnimplementedGrpcService2Server) GetService2(ctx context.Context, req *GetService2Request) (*GetService2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService2 not implemented")
}
func (*UnimplementedGrpcService2Server) GetOtherService2(ctx context.Context, req *GetOtherService2Request) (*GetOtherService2Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOtherService2 not implemented")
}

func RegisterGrpcService2Server(s *grpc.Server, srv GrpcService2Server) {
	s.RegisterService(&_GrpcService2_serviceDesc, srv)
}

func _GrpcService2_GetService2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetService2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcService2Server).GetService2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service2.GrpcService2/GetService2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcService2Server).GetService2(ctx, req.(*GetService2Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrpcService2_GetOtherService2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOtherService2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrpcService2Server).GetOtherService2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service2.GrpcService2/GetOtherService2",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrpcService2Server).GetOtherService2(ctx, req.(*GetOtherService2Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _GrpcService2_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service2.GrpcService2",
	HandlerType: (*GrpcService2Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetService2",
			Handler:    _GrpcService2_GetService2_Handler,
		},
		{
			MethodName: "GetOtherService2",
			Handler:    _GrpcService2_GetOtherService2_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-service-2/service-2.proto",
}
